name: Release
'on':
  push:
    branches:
      - master
      - next
      - alpha
      - next-major
      - beta
      - '*.x'
jobs:
  release:
    name: release
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-node@v2
      #   with:
      #     cache: npm
      #     node-version: 16
      #     cache-dependency-path: 'package.json'
      - run: npm i -g @lytejs/mesh@beta pkg && mesh sync dependencies
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - run: pkg package.json
      - run: mesh npm zip-npm-files
      - run: npx semantic-release
        env:
          HUSKY: 0
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
