name: Release
'on':
  push:
    branches:
      - master
      - next
      - alpha
      - next-major
      - beta
      - '*.x'
jobs:
  mac:
    name: release-mac
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g @lytejs/mesh@beta && mesh sync dependencies
      - run: npm i --legacy-peer-deps
      - run: npm run build
      - run: npm run build:electron
  windows:
    name: release-windows
    runs-on: windows-2022
    steps:
      - run: ls
      - run: npm i --legacy-peer-deps
      - run: npm run build:electron
    needs: mac
  ubuntu:
    name: release-ubuntu
    runs-on: ubuntu-22.04
    steps:
      - run: ls
      - run: npm i --legacy-peer-deps
      - run: npm run build:electron
      - run: cd out && find . -type f
      - run: npx semantic-release
        env:
          HUSKY: 0
          NPM_TOKEN: ${{ secrets.SEMANTIC_RELEASE_BOT_NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: [windows, mac]
